name: example

on:
  push:
    branches: 
      - example

env:
  IMAGE_NAME: web

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    steps:
      - uses: actions/checkout@v4

      - name: Log into registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build . --tag $IMAGE_NAME

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
         
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    steps:
      - name: Deploy
        run: curl ${{ vars.IP }}/?pfolder=${{ secrets.RUTA }}
 
  verify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Wait for 10 seconds before verification
        run: sleep 10
  
      - name: Verify deployment
        run: |
          set -e
          expected_response="informe"  # Text expected on the page
          
          # Make the HTTP request and store the status code
          status_code=$(curl -k -sL -w "%{http_code}" -o /dev/null ${{ vars.DOMAIN }})
          
          if [ "$status_code" -eq 200 ]; then
            # If the status code is 200, check the page content
            page_content=$(curl -k -sL ${{ vars.DOMAIN }})
            if echo "$page_content" | grep -q "$expected_response"; then
              echo "Success: Website is up and returning expected content."
            else
              echo "Error: Website is up, but content check failed."
              exit 1
            fi
          else
            echo "Error: Website returned status code $status_code"
            exit 1
          fi